services:
  web:
    image: evgeniyworkbel/like-volley
    restart: unless-stopped
    # read_only: true (проверить потом)
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - NODE_ENV=production
      - POSTGRES_URL=${POSTGRES_URL}
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
      - NEXT_PUBLIC_YANDEX_METRIKA_COUNTER_ID=${NEXT_PUBLIC_YANDEX_METRIKA_COUNTER_ID}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my_network2

  db:
    image: postgres:18.1-alpine3.23
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}"]
      timeout: 20s
      retries: 10
    networks:
      - my_network2

volumes:
  pgdata:

networks:
  my_network2:
    name: my_network2
    driver: bridge
